name: meetme
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  http: ^0.12.1
  numberpicker: ^1.2.0
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^2.0.1
  string_validator: ^0.1.4
  geolocator: ^5.3.1
  google_maps_flutter: ^0.5.28+1





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - images/orbit.png


  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
    - family: RobotoItalic
      fonts:
        - asset: fonts/Roboto-Italic.ttf